angular
    .module('angle').factory('apiManage', function () {

            var stcFactory = {};
            stcFactory.apiList = {
                'login': { 'api': 'api/Login/userLogin' },
                'userData': { 'api': 'api/user/userData' },
                'menu': { 'api': 'api/user/menu' },
                'clientList': { 'api': 'api/deployment/getClientList' },
                'projectList': { 'api': 'api/deployment/getProjectList' },
                'addDeployment': { 'api':'api/deployment/addDeployment'},
                'getSummaryLive': { 'api': 'api/deployment/getSummaryLive' },
                'getSummaryUAT': { 'api': 'api/deployment/getSummaryUAT' },
                'getSummaryTest': { 'api': 'api/deployment/getSummaryTest' },
                'viewDepDtl': { 'api': 'api/deployment/viewDepDtl' },
                'loanSubmit': { 'api': 'api/loan/createLoan' },
                'entity': { 'api': 'api/entity/entity' },
                'branch': { 'api': 'api/branch/branch' },
                'customer': { 'api': 'api/customer/customer' },
                'customerSubmit': { 'api': 'api/customer/customerSubmit' },
                'loanCreate': { 'api': 'api/loan/loanCreate' },
                'customerSummary': { 'api': 'api/customer/customer' },
                'employee': { 'api': 'api/employee/employee' },
                'loanSummary': { 'api': 'api/loan/loanSummary' },
                'loan_list': { 'api': 'api/loan/loan_list' },
                'getLoanmasterSummary': { 'api': 'api/loan/getLoanmasterSummary' },
                'loan': { 'api': 'api/loan/loan' },
                'customer_getheads': { 'api': 'api/loan/customer_getheads' },
                'Getcustomerdetails': { 'api': 'api/customer/Getcustomerupdatedetails' },
                'customerUpdate': { 'api': 'api/customer/customerUpdate' },
                'customerDelete': { 'api': 'api/customer/customerDelete' },
                'covenanttype_list': { 'api': 'api/covenanttype/getcovenanttype' },
                'covenantTypeSubmit': { 'api': 'api/covenanttype/createcovenanttype' },
                'covenantTypeSummary': { 'api': 'api/covenanttype/getcovenanttype' },
                'GetCovenantType': { 'api': 'api/covenanttype/GetCovenantTypeupdate' },
                'covenantTypeUpdate': { 'api': 'api/covenanttype/covenantTypeUpdate' },
                'covenantTypeDelete': { 'api': 'api/covenanttype/covenantTypeDelete' },
                'deferralmasterSubmit': { 'api': 'api/deferral/deferralmasterSubmit' },
                'Deferralsubmit': { 'api': 'api/deferral/createDeferral' },
                'loan2Deferral': { 'api': 'api/deferral/loan2Deferral' },
                'segment': { 'api': 'api/segment/segment' },
                'Getsegment': { 'api': 'api/segment/Getsegmentupdate' },
                'segmentUpdate': { 'api': 'api/segment/segmentUpdate' },
                'segmentDelete': { 'api': 'api/segment/segmentDelete' },
                'deferral': { 'api': 'api/deferral/deferral' },
                'deferralmasterSummary': { 'api': 'api/deferral/deferralmasterSummary' },
                'Getdeferral': { 'api': 'api/deferral/Getdeferralupdate' },
                'deferralUpdate': { 'api': 'api/deferral/deferralUpdate' },
                'deferralDelete': { 'api': 'api/deferral/deferralDelete' },
                'deferralSummary': { 'api': 'api/deferral/deferralSummary' },
                'customer2loan': { 'api': 'api/deferral/customer2loan' },
                'getLoandetails': { 'api': 'api/loan/getLoandetails' },
                'editloanmaster': { 'api': 'api/loan/editloanmaster' },
                'updateloanmaster': { 'api': 'api/loan/updateloanmaster' },
                'deleteloanmaster': { 'api': 'api/loan/deleteloanmaster' },
                'getdeferralcriticallity': { 'api': 'api/loan/getdeferralcriticallity' },
                'getcovenanttypecriticallity': { 'api': 'api/loan/getcovenanttypecriticallity' },
                'loanUpdate': { 'api': 'api/loan/loanUpdate' },
                'rmDeferralSummary': { 'api': 'api/deferral/rmDeferralSummary' },
                'rm': { 'api': 'api/deferral/rm' },
                'rmdeferraldetails': { 'api': 'api/deferral/rmdeferraldetails' },
                'directDeferralSummary': { 'api': 'api/deferral/directDeferralSummary' },
                'directDeferralSummaryreport': { 'api': 'api/deferral/directDeferralSummaryreport' },
                'export': { 'api': 'api/deferral/export' },
                'uploaddeferraldocument': { 'api': 'api/deferral/UploadDocument' },
                'uploaddeferraldocumentbycad': { 'api': 'api/deferral/uploaddeferraldocumentbycad' },
                'caddocument': { 'api': 'api/deferral/UploadcadDocument' },
                'Getcaddoc': { 'api': 'api/deferral/Getcaddoc' },
                'GetDeferraldoc': { 'api': 'api/deferral/GetDeferraldoc' },
                'GetDetails': { 'api': 'api/deferral/GetDetails' },
                //'Getdeferraldetails': { 'api': 'api/deferral/Getdeferraldetails' },
                'getApprove': { 'api': 'api/deferral/getApprove' },
                'applyExtension': { 'api': 'api/deferral/applyExtension' },
                'extensionSummary': { 'api': 'api/deferral/extensionSummary' },
                'approveExtension': { 'api': 'api/deferral/approveExtension' },
                'deferralApprove': { 'api': 'api/deferral/deferralApprove' },
                'deferralPushback': { 'api': 'api/deferral/deferralPushback' },
                'deferralReject': { 'api': 'api/deferral/deferralReject' },
                'deferralTransfer': { 'api': 'api/deferral/deferralTransfer' },
                'getDeferralDocument': { 'api': 'api/deferral/getDeferralDocument' },
                'getDeferraldetail': { 'api': 'api/deferral/getDeferraldetail' },
                'segmentSummary': { 'api': 'api/segment/segment' },
                'segmentSubmit': { 'api': 'api/segment/createSegment' },
                'segment_list': { 'api': 'api/segment/segmentSummary' },

                // Approvals //
                'taskapprovallist': { 'api': 'api/taskManagement/taskapprovallist' },
                'releasedetails': { 'api': 'api/myApprovals/releasedetails' },
                'issuereleasedetails': { 'api': 'api/myApprovals/issuereleasedetails' },
                'uatdetails': { 'api': 'api/myApprovals/uatdetails' },
                'myapproval': { 'api': 'api/myApprovals/myapproval' },
                'departmentapprove': { 'api': 'api/myApprovals/departmentApproveclick' },
                'departmentreject': { 'api': 'api/myApprovals/departmentreject' },
                'serviceapprove': { 'api': 'api/myApprovals/serviceapprove' },
                'servicereject': { 'api': 'api/myApprovals/servicereject' },
                'manageapprove': { 'api': 'api/myApprovals/manageapprove' },
                'managementreject': { 'api': 'api/myApprovals/managereject' },
                'departmentinternal': { 'api': 'api/myApprovals/departmentinternal' },
                'serviceinternalapprove': { 'api': 'api/myApprovals/serviceinternalapprove' },
                'viewtaskdetails': { 'api': 'api/taskManagement/viewtaskapproval_details' },
                'dependencyapprove': { 'api': 'api/myApprovals/dependencyapprove' },
                'dependencyreject': { 'api': 'api/myApprovals/dependencyreject' },
                'cabapprove': { 'api': 'api/myApprovals/cabapprove' },
                'cabreject': { 'api': 'api/myApprovals/cabreject' },
                'viewdepartment': { 'api': 'api/myApprovals/viewdepartment' },
                'viewservice': { 'api': 'api/myApprovals/viewservice' },
                'viewmanagement': { 'api': 'api/myApprovals/viewmanagement' },

                // New Service Ticket //
                'category_list': { 'api': 'api/newServiceTicket/category' },
                'subcategory_list': { 'api': 'api/newServiceTicket/subcategory' },
                'type_list': { 'api': 'api/newServiceTicket/type' },
                'employee_list': { 'api': 'api/newServiceTicket/employee' },
                'employee_sessioncontact': { 'api': 'api/newServiceTicket/employee_contactdetails' },
                'employee_getcontact': { 'api': 'api/newServiceTicket/employeecontactdetails' },
                'document_tmpclear': { 'api': 'api/newServiceTicket/tmpcleardocument' },
                'raiseticket_submit': { 'api': 'api/newServiceTicket/raiseticket' },
                'uploaddocument': { 'api': 'api/newServiceTicket/UploadDocument' },
                'myasset': { 'api': 'api/viewMyAsset/myasset' },
                'documentdelete': { 'api': 'api/newServiceTicket/documentdelete' },
                'view_ticket': { 'api': 'api/viewServiceTicket/ticketdetails_view' },
                'viewdocument': { 'api': 'api/viewServiceTicket/viewdocument' },
                'viewserviceticket': { 'api': 'api/viewServiceTicket/viewserviceticket' },
                'ticketclose': { 'api': 'api/viewServiceTicket/closeticket' },
                'responselog_submit': { 'api': 'api/viewServiceTicket/response_logdetails' },
                'incompleteticket': { 'api': 'api/viewServiceTicket/incompleteticket' },
                'responselogdetails_view': { 'api': 'api/viewServiceTicket/responselogdetails_view' },

                // Asset... //
                'notification': { 'api': 'api/landingPage/landingpagedata' },
                'SValues': { 'api': 'api/AdminLogin/SValues' },
                'myasset': { 'api': 'api/viewMyAsset/myasset' },
                'holdingasset': { 'api': 'api/temporaryHandover/holdingasset' },
                'surrenderitadmin': { 'api': 'api/temporaryHandover/surrenderitadmin' },
                'surrender': { 'api': 'api/surrenderAsset/surrender' },
                'temporaryhandover': { 'api': 'api/temporaryHandover/tmphandover' },
                'temporaryhandoversubmit': { 'api': 'api/temporaryHandover/submittmphandover' },
                'surrenderitadmin': { 'api': 'api/temporaryHandover/surrenderitadmin' },
                'acknowledgement': { 'api': 'api/acknowledgeMyAsset/acknowledgement' },
                'submitacknowledgement': { 'api': 'api/acknowledgeMyAsset/submitacknowledgement' },
                'rejectacknowledgement': { 'api': 'api/acknowledgeMyAsset/acknowledgementreject' },
                'submitsurrender': { 'api': 'api/surrenderAsset/submitsurrender' }
                           };
            return stcFactory;
        });