//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ems.master.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.test.transuniondecisioncentre.co.in/DC/TUCL/TU.IDS.ExternalServices/S" +
            "olutionExecution/ExternalSolutionExecution.svc")]
        public string ems_master_TransUnionCommService_ExternalSolutionExecutionService {
            get {
                return ((string)(this["ems_master_TransUnionCommService_ExternalSolutionExecutionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.test.transuniondecisioncentre.co.in/DC/TU/TU.IDS.ExternalServices/Sol" +
            "utionExecution/ExternalSolutionExecution.svc")]
        public string ems_master_TransUnionService_ExternalSolutionExecutionService {
            get {
                return ((string)(this["ems_master_TransUnionService_ExternalSolutionExecutionService"]));
            }
        }
    }
}
